### ISSUE TITLE
UI Changes 2/25/17

### ISSUE THREAD

**Issue by PatrickWieland** [DigiByteMiner/DigiByteMiner#3]
1. Any reference of “DigiByte” needs to display Digi”B”yte capital B 

2. Swap Nvidia/AMD logo in GPU info window for Images of a GPU instead of company logo 

3. exe title “Digibyte One Click Miner” 

4. Upper Case “SETTINGS” “HELP” on top bar. 

5. Top UI bar where settings/Help are change white color to a a darker contrast color. 

6. Let’s move “Pool Info” over to left to line it up with the rest of the info. Can we make an embossed button to highlight this instead of just the Pool Info link? 

7. Line up “Profile” in line with algorithm server etc so it’s lined up. 

8. Line up “DigiByte Miner” with rest of the info in the top window like mentioned above. Also capitalize “DIGIBYTE MINER” here.

**Comment by arunsatyarth** [comment]
Done in version 0.3
